---

- name: Copy Bika NGINX configuration
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx
  tags: bika-nginx

- name: Copy Bika NGINX Config
  template:
    src: bika.conf.j2
    dest: "{{ nginx_vhost_path }}/bika.conf"
    mode: 0644
  notify:
    - reload nginx
  tags: bika-nginx
