---

- hosts: all
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: Include Vagrant Variables `vagrant_configure.yml`
      include_vars: vagrant_configure.yml
  roles:
    - role: bika

  tasks:
    # make sure Plone Daemons have had time to come up
    - pause: minutes=1

    - pip: name=httplib2

    - name: Check to see if Bika is running
      uri:
        url: http://127.0.0.1:80/bikalims
        method: GET
        status_code: 200
