---

- hosts: all
  become: yes

  roles:
    - role: bika

  tasks:
    # make sure Plone Daemons have had time to come up
    - pause: minutes=1

    - pip: name=httplib2

    - name: Check to see if Bika is running
      uri:
        url: http://127.0.0.1/bikalims
        method: GET
        status_code: 200
