---

# Bika Plone
bika_plone_additional_eggs:
  - bika.lims
bika_plone_additional_versions:
  - bika.lims=3.1.11
bika_plone_extension_profiles:
  - bika.lims:default
bika_plone_client_count: 2
bika_plone_initial_password: admin

# Supervisor HTTP UI
bika_supervisor_with_http: yes
bika_supervisor_http_user: admin
bika_supervisor_http_pass: admin

# HAProxy
bika_haproxy_with_http_stats: yes
bika_haproxy_stats_user: admin
bika_haproxy_stats_pass: admin
bika_haproxy_frontend_bind_address: "127.0.0.1"
bika_haproxy_frontend_port: "8080"

# Varnish Backend (HAProxy)
bika_varnish_default_backend_host: "127.0.0.1"
bika_varnish_default_backend_port: "8080"
# Varnish Frontend (used by NGINX as upstream)
bika_varnish_listen_port: "8888"

# NGINX (Frontend)
bika_vhosts:
  - example.bikalabs.com

bika_ssl_certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
bika_ssl_certificate_key: /etc/ssl/private/ssl-cert-snakeoil.key

# Security Settings
bika_firewall_open_tcp_ports: [80, 443]
bika_firewall_use_fail2ban: yes
