---

- name: Fail if Ansible version is too old
  fail: msg="Ansible version too old, please update your kit. 'pip install -U Ansible'"
  when: ansible_version.major < 2

- name: Setting variables for -> {{ ansible_distribution }}
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
  tags:
    - bika-base

- name: Update APT package cache
  action: apt update_cache=yes
  when: ansible_os_family == "Debian"
  tags:
    - bika-base
    - bika-apt
- name: Update YUM package cache
  action: yum update_cache=yes
  when: ansible_os_family == "RedHat"
  tags:
    - bika-base
    - bika-apt

- name: Upgrade APT to the lastest packages
  action: apt upgrade=full
  when: ansible_os_family == "Debian"
#  notify: reboot
  tags:
    - bika-base
    - bika-apt

- name: Upgrade YUM to the lastest packages
  action: yum upgrade=full
  when: ansible_os_family == "RedHat"
#  notify: reboot
  tags:
    - bika-base
    - bika-apt

- name: Install required packages
  apt: state=installed pkg=unattended-upgrades
#  notify: reboot
  when: bika_apt_unattended_upgrade == 1
  tags:
    - bika-base

- name: Install packages for -> {{ ansible_distribution }}
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ bika_packages }}"
  tags:
    - bika-base

- name: Install additional system packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ bika_additional_system_packages }}"
  tags:
    - bika-base

- name: Adjust APT update intervals
  template:
    src: 10periodic.j2
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == "Debian"
  tags:
    - bika-base
